name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-Windows:
    name: Build For Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: pwsh
        run: |
          cmake -B build
          cmake --build build
